#!/bin/bash

echo "🎨 拼豆管理系统 - 单文件版"
echo ""
echo "文件位置："
echo "/root/.openclaw/workspace/pindou-manager/pindou-manager-standalone.html"
echo ""
echo "文件大小：234 KB"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📥 下载方法："
echo ""
echo "1. 使用 scp 下载到本地："
echo "   scp root@$(curl -s ifconfig.me):/root/.openclaw/workspace/pindou-manager/pindou-manager-standalone.html ~/Downloads/拼豆管理系统.html"
echo ""
echo "2. 或者在服务器上运行以下命令启动下载服务器："
echo "   cd /root/.openclaw/workspace/pindou-manager"
echo "   python3 -m http.server 8888"
echo "   然后访问: http://$(curl -s ifconfig.me):8888/pindou-manager-standalone.html"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ 使用方法："
echo ""
echo "下载后直接双击 HTML 文件即可在浏览器中打开使用！"
echo ""
echo "- 完全离线可用"
echo "- 数据保存在浏览器本地"
echo "- 支持手机、平板、电脑"
echo ""
echo "详细说明请查看: STANDALONE_GUIDE.md"
echo ""
